apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app2
  template:
    metadata:
      labels:
        app: demo-app2
    spec:
      containers:
        - name: demo-app2
          image: ghcr.io/fezhou2/demo-app2:latest
          # env:
          # - name: SECRET
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secret
          #       key: secret-key
          ports:
            - containerPort: 8080
